/*
 * This code is derived from MyJavaLibrary (http://somelinktomycoollibrary)
 * 
 * If this is an open source Java library, include the proper license and copyright attributions here!
 */

using Org.Apache.Lucene.Queryparser.Ext;
using Org.Apache.Lucene.Search;
using Sharpen;

namespace Org.Apache.Lucene.Queryparser.Ext
{
	/// <summary>
	/// This class represents an extension base class to the Lucene standard
	/// <see cref="Org.Apache.Lucene.Queryparser.Classic.QueryParser">Org.Apache.Lucene.Queryparser.Classic.QueryParser
	/// 	</see>
	/// . The
	/// <see cref="Org.Apache.Lucene.Queryparser.Classic.QueryParser">Org.Apache.Lucene.Queryparser.Classic.QueryParser
	/// 	</see>
	/// is generated by the JavaCC
	/// parser generator. Changing or adding functionality or syntax in the standard
	/// query parser requires changes to the JavaCC source file. To enable extending
	/// the standard query parser without changing the JavaCC sources and re-generate
	/// the parser the
	/// <see cref="ParserExtension">ParserExtension</see>
	/// can be customized and plugged into an
	/// instance of
	/// <see cref="ExtendableQueryParser">ExtendableQueryParser</see>
	/// , a direct subclass of
	/// <see cref="Org.Apache.Lucene.Queryparser.Classic.QueryParser">Org.Apache.Lucene.Queryparser.Classic.QueryParser
	/// 	</see>
	/// .
	/// </summary>
	/// <seealso cref="Extensions">Extensions</seealso>
	/// <seealso cref="ExtendableQueryParser">ExtendableQueryParser</seealso>
	public abstract class ParserExtension
	{
		/// <summary>
		/// Processes the given
		/// <see cref="ExtensionQuery">ExtensionQuery</see>
		/// and returns a corresponding
		/// <see cref="Org.Apache.Lucene.Search.Query">Org.Apache.Lucene.Search.Query</see>
		/// instance. Subclasses must either return a
		/// <see cref="Org.Apache.Lucene.Search.Query">Org.Apache.Lucene.Search.Query</see>
		/// instance or raise a
		/// <see cref="Org.Apache.Lucene.Queryparser.Classic.ParseException">Org.Apache.Lucene.Queryparser.Classic.ParseException
		/// 	</see>
		/// . This method must not return
		/// <code>null</code>.
		/// </summary>
		/// <param name="query">the extension query</param>
		/// <returns>a new query instance</returns>
		/// <exception cref="Org.Apache.Lucene.Queryparser.Classic.ParseException">if the query can not be parsed.
		/// 	</exception>
		public abstract Query Parse(ExtensionQuery query);
	}
}
