# Apache YAML Features for Git Repositories
# See the documentation at: https://github.com/apache/infrastructure-asfyaml/blob/main/README.md

# See our mailing lists here: https://lucenenet.apache.org/contributing/mailing-lists.html
notifications:
  commits: commits@lucenenet.apache.org
  issues: dev@lucenenet.apache.org
  pullrequests: dev@lucenenet.apache.org
  discussions: dev@lucenenet.apache.org
  # jobs: builds@lucenenet.apache.org # This is probably too noisy to enable

github:
  description: "Apache Lucene.NET"
  homepage: https://lucenenet.apache.org/
  labels:
    - lucenenet
    - lucene
    - text
    - search
    - information
    - retrieval
    - analysis
    - index
    - query
    - apache
    - hacktoberfest
    
  features:
    # Enable wiki for documentation
    wiki: false
    # Enable issues management
    issues: true
    # Enable projects for project management boards
    projects: false
    # Enable discussions
    discussions: true

  # Disallow forced pushes
  protected_branches:
    master: {}
