# Apache YAML Features for Git Repositories
# See the documentation at: https://github.com/apache/infrastructure-asfyaml/blob/main/README.md

# See our mailing lists here: https://lucenenet.apache.org/contributing/mailing-lists.html
notifications:
  commits: commits@lucenenet.apache.org
  issues: dev@lucenenet.apache.org
  pullrequests: dev@lucenenet.apache.org
  discussions: dev@lucenenet.apache.org
  # jobs: builds@lucenenet.apache.org # This is probably too noisy to enable

github:
  description: "Apache Lucene.NET is an open-source full-text search library written in C#, ported from the Apache Lucene project."
  homepage: https://lucenenet.apache.org/
  labels:
    - lucenenet
    - lucene
    - text
    - search
    - information
    - retrieval
    - analysis
    - index
    - query
    - apache
    - hacktoberfest

  features:
    # Enable wiki for documentation
    wiki: false
    # Enable issues management
    issues: true
    # Enable projects for project management boards
    projects: false
    # Enable discussions
    discussions: true

  enabled_merge_buttons:
    squash:  true
    # default commit message when merging with a squash commit
    # can either be: DEFAULT | PR_TITLE | PR_TITLE_AND_COMMIT_DETAILS | PR_TITLE_AND_DESC
    squash_commit_message: PR_TITLE
    merge: false
    rebase: false

  rulesets:
    - name: "Branch Protection"
      type: branch
      branches:
        includes:
          - "master"
          - "docs/*"
        excludes: []
      bypass_teams:
        - root
      restrict_deletion: true
      restrict_force_push: true
      required_linear_history: true
      required_conversation_resolution: true
      required_pull_request_reviews:
        dismiss_stale_reviews: false
        require_last_push_approval: false
        require_code_owner_reviews: false
        required_approving_review_count: 0
    - name: "Release Branch Protection"
      type: branch
      branches:
        includes:
          - "release/*"
        excludes: []
      bypass_teams:
        - root
      restrict_deletion: true
      restrict_force_push: false
      required_linear_history: false
