# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

---
# https://pre-commit.com/#installation
default_stages: [pre-commit, pre-push]
default_language_version:
  # force all unspecified Python hooks to run python3
  python: python3
minimum_pre_commit_version: '3.2.0'
repos:
  - repo: meta
    hooks:
      - id: identity
        name: run identity check
        description: check you have set your git identity
      - id: check-hooks-apply
        name: run check hooks apply
        description: check that all the hooks apply to the repository
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell
        name: run codespell
        description: check spelling with codespell
        exclude: ^src/Lucene\.Net\.Analysis\.Common/Analysis/../.*\.rslp$|^.*Lucene\.Net\.Tests.*$
        args: [--ignore-words=.github/linters/codespell.txt]
  - repo: https://github.com/oxipng/oxipng
    rev: v10.1.0
    hooks:
      - id: oxipng
        name: run oxipng
        description: check PNG files with oxipng
        args: [ '--fix', '-o', '4', '--strip', 'safe', '--alpha' ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        name: run trailing-whitespace
        description: trims trailing whitespace
        files: \.(md|xml|ya?ml)$
        args: [--markdown-linebreak-ext=md]
      - id: check-case-conflict
        name: run check-case-conflict
        description: check for case conflicts in file names
      - id: check-illegal-windows-names
        name: run check-illegal-windows-names
        description: check for Windows-illegal file names
      - id: check-merge-conflict
        name: run check-merge-conflict
        description: check for merge conflict markers
      - id: check-vcs-permalinks
        name: run check-vcs-permalinks
        description: ensures that links to vcs websites are permalinks
      - id: detect-private-key
        name: run detect-private-key
        description: checks for the existence of private keys
      - id: forbid-submodules
        name: run forbid-submodules
        description: forbids any submodules in the repository
      - id: fix-byte-order-marker
        name: run fix-byte-order-marker
        description: fixes files with UTF-8 byte order markers
