#! /usr/bin/env bash
# -----------------------------------------------------------------------------------
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the ""License""); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an ""AS IS"" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# -----------------------------------------------------------------------------------
#
# This file will build Lucene.Net and create the NuGet packages.
#
# Syntax:
#   build[.bat] [<options>]
#
# Available Options:
#
#   --file-version <FileVersion>
#   -fv <FileVersion> - File version number. If not supplied, the file version will be the same
#                  as PackageVersion (excluding any pre-release tag). This value is not allowed
#                  if there is a version.props file (which is included in the release distribution).
#
#   --package-version <PackageVersion>
#   -pv <PackageVersion> - Nuget package version. Default is the value defined in Directory.Build.props.
#                  This value is not allowed if there is a version.props file (which is included in the
#                  release distribution).
#
#   --configuration <Configuration>
#   -config <Configuration> - MSBuild configuration for the build.
#
#   --test
#   -t - Run the tests.
#
#   --maximum-parallel-jobs
#   -mp - Set the maxumum number of parallel jobs to run during testing. If not supplied, the default is 8.
#
#   All options are case insensitive.
#
# -----------------------------------------------------------------------------------
if ! command -v pwsh &> /dev/null
then
    echo "Powershell Core could not be found. Please install version 3 or higher."
    exit
fi
pwsh -ExecutionPolicy bypass -Command "& './build.ps1'" "$@"