// Lucene version compatibility level 4.8.1
using Lucene.Net.Analysis;
using Lucene.Net.Analysis.TokenAttributes;
using Lucene.Net.Util;
using System;
using System.Globalization;

namespace Lucene.Net.Collation
{
    /*
     * Licensed to the Apache Software Foundation (ASF) under one or more
     * contributor license agreements.  See the NOTICE file distributed with
     * this work for additional information regarding copyright ownership.
     * The ASF licenses this file to You under the Apache License, Version 2.0
     * (the "License"); you may not use this file except in compliance with
     * the License.  You may obtain a copy of the License at
     *
     *     http://www.apache.org/licenses/LICENSE-2.0
     *
     * Unless required by applicable law or agreed to in writing, software
     * distributed under the License is distributed on an "AS IS" BASIS,
     * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     * See the License for the specific language governing permissions and
     * limitations under the License.
     */

    /// <summary>
    /// <para>
    ///   Converts each token into its <see cref="System.Globalization.SortKey"/>, and then
    ///   encodes the <see cref="System.Globalization.SortKey"/> with <see cref="IndexableBinaryStringTools"/>, to allow
    ///   it to be stored as an index term.
    /// </para>
    /// <para>
    ///   <strong>WARNING:</strong> Make sure you use exactly the same <see cref="CompareInfo"/> at
    ///   index and query time -- <see cref="System.Globalization.SortKey"/> are only comparable when produced by
    ///   the same <see cref="CompareInfo"/>.  Since the platform collator is not
    ///   independently versioned, it is unsafe to search against stored
    ///   <see cref="System.Globalization.SortKey"/> unless the following are exactly the same (best practice is
    ///   to store this information with the index and check that they remain the
    ///   same at query time):
    /// </para>
    /// <list type="number">
    ///   <item><description>The .NET runtime version</description></item>
    ///   <item><description>
    ///     The <see cref="CultureInfo"/> of the <see cref="CompareInfo"/> obtained via
    ///     <see cref="CompareInfo.GetCompareInfo(string)"/>.
    ///   </description></item>
    ///   <item><description>
    ///     The <see cref="CompareOptions"/> used - which control the collation strength
    ///     and Unicode normalization.
    ///   </description></item>
    /// </list>
    /// <para>
    ///   The <c>ICUCollationKeyFilter</c> in the Lucene.Net.ICU package
    ///   uses ICU4N's Collator, which makes its
    ///   version available, thus allowing collation to be versioned independently
    ///   from the .NET runtime.  ICUCollationKeyFilter generates significantly
    ///   shorter keys than <see cref="CollationKeyFilter"/> and exposes tailoring/custom
    ///   rules that the platform collator does not support.
    /// </para>
    /// <para>
    ///   <see cref="System.Globalization.SortKey"/>s generated by the platform collator are not compatible
    ///   with those generated by ICU Collators.  Specifically, if you use
    ///   <see cref="CollationKeyFilter"/> to generate index terms, do not use
    ///   ICUCollationKeyFilter on the query side, or vice versa.
    /// </para> </summary>
    /// @deprecated Use <see cref="CollationAttributeFactory"/> instead, which encodes
    ///  terms directly as bytes. This filter will be removed in Lucene 5.0
    [Obsolete("Use CollationAttributeFactory instead, which encodes terms directly as bytes. This filter will be removed in Lucene 5.0.")]
    public sealed class CollationKeyFilter : TokenFilter
    {
        private readonly CompareInfo collator;
        private readonly CompareOptions options;
        private readonly ICharTermAttribute termAtt;

        /// <param name="input"> Source token stream </param>
        /// <param name="collator"> <see cref="System.Globalization.SortKey"/> generator </param>
        public CollationKeyFilter(TokenStream input, CompareInfo collator)
            : this(input, collator, CompareOptions.None)
        {
        }

        /// <param name="input"> Source token stream </param>
        /// <param name="collator"> <see cref="System.Globalization.SortKey"/> generator </param>
        /// <param name="options"> Collation options that control the collation strength and
        /// Unicode normalization (decomposition) of the generated sort key. </param>
        public CollationKeyFilter(TokenStream input, CompareInfo collator, CompareOptions options)
            : base(input)
        {
            this.collator = collator;
            this.options = options;
            this.termAtt = this.AddAttribute<ICharTermAttribute>();
        }

        public override bool IncrementToken()
        {
            if (this.m_input.IncrementToken())
            {
                byte[] collationKey = GetCollationKey();
                int encodedLength = IndexableBinaryStringTools.GetEncodedLength(collationKey, 0, collationKey.Length);
                this.termAtt.ResizeBuffer(encodedLength);
                this.termAtt.Length = encodedLength;

                IndexableBinaryStringTools.Encode(collationKey, 0, collationKey.Length, this.termAtt.Buffer, 0, encodedLength);
                return true;
            }
            else
            {
                return false;
            }
        }

        private byte[] GetCollationKey()
        {
#if FEATURE_COMPAREINFO_GETSORTKEY_SPAN
            // LUCENENET: On .NET 5+ with ICU, CompareInfo has a ReadOnlySpan<char> overload of GetSortKey
            // that lets us generate the sort key without converting the term to a string first. The NLS
            // backend does not normalize internally (see CollatedTermAttribute.Normalize), so we still need
            // the slow path when the app is configured for NLS.
            if (CollationUtil.IsICU)
            {
                ReadOnlySpan<char> source = this.termAtt.Buffer.AsSpan(0, this.termAtt.Length);
                byte[] collationKey = new byte[this.collator.GetSortKeyLength(source, this.options)];
                this.collator.GetSortKey(source, collationKey, this.options);
                return collationKey;
            }
#endif
            // LUCENENET: Normalize to NFC for cross-backend consistency. See CollatedTermAttribute.Normalize.
            return this.collator.GetSortKey(TokenAttributes.CollatedTermAttribute.Normalize(this.termAtt.ToString()), this.options).KeyData;
        }
    }
}
