// Lucene version compatibility level 4.8.1
using Lucene.Net.Collation.TokenAttributes;
using Lucene.Net.Util;
using System.Globalization;

namespace Lucene.Net.Collation
{
    /*
     * Licensed to the Apache Software Foundation (ASF) under one or more
     * contributor license agreements.  See the NOTICE file distributed with
     * this work for additional information regarding copyright ownership.
     * The ASF licenses this file to You under the Apache License, Version 2.0
     * (the "License"); you may not use this file except in compliance with
     * the License.  You may obtain a copy of the License at
     *
     *     http://www.apache.org/licenses/LICENSE-2.0
     *
     * Unless required by applicable law or agreed to in writing, software
     * distributed under the License is distributed on an "AS IS" BASIS,
     * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     * See the License for the specific language governing permissions and
     * limitations under the License.
     */

    /// <summary>
    /// <para>
    ///   Converts each token into its <see cref="System.Globalization.SortKey"/>, and then
    ///   encodes the bytes as an index term.
    /// </para>
    /// <para>
    ///   <strong>WARNING:</strong> Make sure you use exactly the same <see cref="CompareInfo"/> at
    ///   index and query time -- <see cref="System.Globalization.SortKey"/>s are only comparable when produced by
    ///   the same <see cref="CompareInfo"/>.  Since the platform collator is not
    ///   independently versioned, it is unsafe to search against stored
    ///   <see cref="System.Globalization.SortKey"/>s unless the following are exactly the same (best practice is
    ///   to store this information with the index and check that they remain the
    ///   same at query time):
    /// </para>
    /// <list type="number">
    ///   <item><description>The .NET runtime version</description></item>
    ///   <item><description>
    ///     The <see cref="CultureInfo"/> of the <see cref="CompareInfo"/> obtained via
    ///     <see cref="CompareInfo.GetCompareInfo(string)"/>.
    ///   </description></item>
    ///   <item><description>
    ///     The <see cref="CompareOptions"/> used - which control the collation strength
    ///     and Unicode normalization.
    ///   </description></item>
    /// </list>
    /// <para>
    ///   The <c>ICUCollationAttributeFactory</c> in the Lucene.Net.ICU package
    ///   uses ICU4N's Collator, which makes its
    ///   version available, thus allowing collation to be versioned independently
    ///   from the .NET runtime.  ICUCollationAttributeFactory generates
    ///   significantly shorter keys than <see cref="CollationAttributeFactory"/> and exposes
    ///   tailoring/custom rules that the platform collator does not support.
    /// </para>
    /// <para>
    ///   <see cref="System.Globalization.SortKey"/>s generated by the platform collator are not compatible
    ///   with those generated by ICU Collators.  Specifically, if you use
    ///   <see cref="CollationAttributeFactory"/> to generate index terms, do not use
    ///   ICUCollationAttributeFactory on the query side, or vice versa.
    /// </para>
    /// </summary>
    public class CollationAttributeFactory : AttributeFactory
    {
        private readonly CompareInfo collator;
        private readonly CompareOptions options;
        private readonly AttributeFactory @delegate;

        /// <summary>
        /// Create a <see cref="CollationAttributeFactory"/>, using
        /// <see cref="AttributeFactory.DEFAULT_ATTRIBUTE_FACTORY"/> as the
        /// factory for all other attributes. </summary>
        /// <param name="collator"> <see cref="System.Globalization.SortKey"/> generator </param>
        public CollationAttributeFactory(CompareInfo collator)
            : this(AttributeFactory.DEFAULT_ATTRIBUTE_FACTORY, collator, CompareOptions.None)
        {
        }

        /// <summary>
        /// Create a <see cref="CollationAttributeFactory"/>, using
        /// <see cref="AttributeFactory.DEFAULT_ATTRIBUTE_FACTORY"/> as the
        /// factory for all other attributes. </summary>
        /// <param name="collator"> <see cref="System.Globalization.SortKey"/> generator </param>
        /// <param name="options"> Collation options that control the collation strength and
        /// Unicode normalization (decomposition) of the generated sort key. </param>
        public CollationAttributeFactory(CompareInfo collator, CompareOptions options)
            : this(AttributeFactory.DEFAULT_ATTRIBUTE_FACTORY, collator, options)
        {
        }

        /// <summary>
        /// Create a <see cref="CollationAttributeFactory"/>, using the supplied Attribute Factory
        /// as the factory for all other attributes. </summary>
        /// <param name="delegate"> Attribute Factory </param>
        /// <param name="collator"> <see cref="System.Globalization.SortKey"/> generator </param>
        public CollationAttributeFactory(AttributeFactory @delegate, CompareInfo collator)
            : this(@delegate, collator, CompareOptions.None)
        {
        }

        /// <summary>
        /// Create a <see cref="CollationAttributeFactory"/>, using the supplied Attribute Factory
        /// as the factory for all other attributes. </summary>
        /// <param name="delegate"> Attribute Factory </param>
        /// <param name="collator"> <see cref="System.Globalization.SortKey"/> generator </param>
        /// <param name="options"> Collation options that control the collation strength and
        /// Unicode normalization (decomposition) of the generated sort key. </param>
        public CollationAttributeFactory(AttributeFactory @delegate, CompareInfo collator, CompareOptions options)
        {
            this.@delegate = @delegate;
            this.collator = collator;
            this.options = options;
        }

        public override Attribute CreateAttributeInstance<T>()
        {
            return typeof(T).IsAssignableFrom(typeof(CollatedTermAttribute))
                ? new CollatedTermAttribute(this.collator, this.options)
                : this.@delegate.CreateAttributeInstance<T>();
        }
    }
}
