namespace Lucene.Net.Tartarus.Snowball.Ext
{
    /// <summary>
    /// This class was automatically generated by a Snowball to Java compiler
    /// It implements the stemming algorithm defined by a snowball script.
    /// </summary>
    public class GermanStemmer : SnowballProgram
    {
        private readonly static GermanStemmer methodObject = new GermanStemmer();

        private readonly static Among[] a_0 = {
                    new Among ( "", -1, 6, "", methodObject ),
                    new Among ( "U", 0, 2, "", methodObject ),
                    new Among ( "Y", 0, 1, "", methodObject ),
                    new Among ( "\u00E4", 0, 3, "", methodObject ),
                    new Among ( "\u00F6", 0, 4, "", methodObject ),
                    new Among ( "\u00FC", 0, 5, "", methodObject )
                };

        private readonly static Among[] a_1 = {
                    new Among ( "e", -1, 1, "", methodObject ),
                    new Among ( "em", -1, 1, "", methodObject ),
                    new Among ( "en", -1, 1, "", methodObject ),
                    new Among ( "ern", -1, 1, "", methodObject ),
                    new Among ( "er", -1, 1, "", methodObject ),
                    new Among ( "s", -1, 2, "", methodObject ),
                    new Among ( "es", 5, 1, "", methodObject )
                };

        private readonly static Among[] a_2 = {
                    new Among ( "en", -1, 1, "", methodObject ),
                    new Among ( "er", -1, 1, "", methodObject ),
                    new Among ( "st", -1, 2, "", methodObject ),
                    new Among ( "est", 2, 1, "", methodObject )
                };

        private readonly static Among[] a_3 = {
                    new Among ( "ig", -1, 1, "", methodObject ),
                    new Among ( "lich", -1, 1, "", methodObject )
                };

        private readonly static Among[] a_4 = {
                    new Among ( "end", -1, 1, "", methodObject ),
                    new Among ( "ig", -1, 2, "", methodObject ),
                    new Among ( "ung", -1, 1, "", methodObject ),
                    new Among ( "lich", -1, 3, "", methodObject ),
                    new Among ( "isch", -1, 2, "", methodObject ),
                    new Among ( "ik", -1, 2, "", methodObject ),
                    new Among ( "heit", -1, 3, "", methodObject ),
                    new Among ( "keit", -1, 4, "", methodObject )
                };

        private static readonly char[] g_v = { (char)17, (char)65, (char)16, (char)1, (char)0, (char)0, (char)0, (char)0, (char)0, (char)0, (char)0, (char)0, (char)0, (char)0, (char)0, (char)0, (char)8, (char)0, (char)32, (char)8 };

        private static readonly char[] g_s_ending = { (char)117, (char)30, (char)5 };

        private static readonly char[] g_st_ending = { (char)117, (char)30, (char)4 };

        private int I_x;
        private int I_p2;
        private int I_p1;

        private void copy_from(GermanStemmer other)
        {
            I_x = other.I_x;
            I_p2 = other.I_p2;
            I_p1 = other.I_p1;
            base.copy_from(other);
        }

        private bool r_prelude()
        {
            int v_1;
            int v_2;
            int v_3;
            int v_4;
            int v_5;
            int v_6;
            // (, line 28
            // test, line 30
            v_1 = cursor;
            // repeat, line 30
            
            while (true)
            {
                v_2 = cursor;
                
                do
                {
                    // (, line 30
                    // or, line 33
                    
                    do
                    {
                        v_3 = cursor;
                        
                        do
                        {
                            // (, line 31
                            // [, line 32
                            bra = cursor;
                            // literal, line 32
                            if (!(eq_s(1, "\u00DF")))
                            {
                                goto lab3;
                            }
                            // ], line 32
                            ket = cursor;
                            // <-, line 32
                            slice_from("ss");
                            goto lab2;
                        } while (false);
                        lab3:
                        cursor = v_3;
                        // next, line 33
                        if (cursor >= limit)
                        {
                            goto lab1;
                        }
                        cursor++;
                    } while (false);
                    lab2:
                    // LUCENENET NOTE: continue label is not supported directly in .NET,
                    // so we just need to add another goto to get to the end of the outer loop.
                    // See: http://stackoverflow.com/a/359449/181087

                    // Original code:
                    //continue replab0;

                    goto end_of_outer_loop;
                    
                } while (false);
                lab1:
                cursor = v_2;
                goto replab0;
                end_of_outer_loop: { }
            }
            replab0:
            cursor = v_1;
            // repeat, line 36
           
            while (true)
            {
                v_4 = cursor;
                
                do
                {
                    // goto, line 36
                    
                    while (true)
                    {
                        v_5 = cursor;
                        
                        do
                        {
                            // (, line 36
                            if (!(in_grouping(g_v, 97, 252)))
                            {
                                goto lab7;
                            }
                            // [, line 37
                            bra = cursor;
                            // or, line 37
                            
                            do
                            {
                                v_6 = cursor;
                                
                                do
                                {
                                    // (, line 37
                                    // literal, line 37
                                    if (!(eq_s(1, "u")))
                                    {
                                        goto lab9;
                                    }
                                    // ], line 37
                                    ket = cursor;
                                    if (!(in_grouping(g_v, 97, 252)))
                                    {
                                        goto lab9;
                                    }
                                    // <-, line 37
                                    slice_from("U");
                                    goto lab8;
                                } while (false);
                                lab9:
                                cursor = v_6;
                                // (, line 38
                                // literal, line 38
                                if (!(eq_s(1, "y")))
                                {
                                    goto lab7;
                                }
                                // ], line 38
                                ket = cursor;
                                if (!(in_grouping(g_v, 97, 252)))
                                {
                                    goto lab7;
                                }
                                // <-, line 38
                                slice_from("Y");
                            } while (false);
                            lab8:
                            cursor = v_5;
                            goto golab6;
                        } while (false);
                        lab7:
                        cursor = v_5;
                        if (cursor >= limit)
                        {
                            goto lab5;
                        }
                        cursor++;
                    }
                    golab6:
                    // LUCENENET NOTE: continue label is not supported directly in .NET,
                    // so we just need to add another goto to get to the end of the outer loop.
                    // See: http://stackoverflow.com/a/359449/181087

                    // Original code:
                    //continue replab4;

                    goto end_of_outer_loop_2;
                    
                } while (false);
                lab5:
                cursor = v_4;
                goto replab4;
                end_of_outer_loop_2: { }
            }
            replab4:
            return true;
        }

        private bool r_mark_regions()
        {
            int v_1;
            // (, line 42
            I_p1 = limit;
            I_p2 = limit;
            // test, line 47
            v_1 = cursor;
            // (, line 47
            // hop, line 47
            {
                int c = cursor + 3;
                if (0 > c || c > limit)
                {
                    return false;
                }
                cursor = c;
            }
            // setmark x, line 47
            I_x = cursor;
            cursor = v_1;
            // gopast, line 49
            
            while (true)
            {
                
                do
                {
                    if (!(in_grouping(g_v, 97, 252)))
                    {
                        goto lab1;
                    }
                    goto golab0;
                } while (false);
                lab1:
                if (cursor >= limit)
                {
                    return false;
                }
                cursor++;
            }
            golab0:
            // gopast, line 49
            
            while (true)
            {
                
                do
                {
                    if (!(out_grouping(g_v, 97, 252)))
                    {
                        goto lab3;
                    }
                    goto golab2;
                } while (false);
                lab3:
                if (cursor >= limit)
                {
                    return false;
                }
                cursor++;
            }
            golab2:
            // setmark p1, line 49
            I_p1 = cursor;
            // try, line 50
            
            do
            {
                // (, line 50
                if (!(I_p1 < I_x))
                {
                    goto lab4;
                }
                I_p1 = I_x;
            } while (false);
            lab4:
            // gopast, line 51
            
            while (true)
            {
                do
                {
                    if (!(in_grouping(g_v, 97, 252)))
                    {
                        goto lab6;
                    }
                    goto golab5;
                } while (false);
                lab6:
                if (cursor >= limit)
                {
                    return false;
                }
                cursor++;
            }
            golab5:
            // gopast, line 51
            
            while (true)
            {
                
                do
                {
                    if (!(out_grouping(g_v, 97, 252)))
                    {
                        goto lab8;
                    }
                    goto golab7;
                } while (false);
                lab8:
                if (cursor >= limit)
                {
                    return false;
                }
                cursor++;
            }
            golab7:
            // setmark p2, line 51
            I_p2 = cursor;
            return true;
        }

        private bool r_postlude()
        {
            int among_var;
            int v_1;
            // repeat, line 55
            
            while (true)
            {
                v_1 = cursor;
                
                do
                {
                    // (, line 55
                    // [, line 57
                    bra = cursor;
                    // substring, line 57
                    among_var = find_among(a_0, 6);
                    if (among_var == 0)
                    {
                        goto lab1;
                    }
                    // ], line 57
                    ket = cursor;
                    switch (among_var)
                    {
                        case 0:
                            goto lab1;
                        case 1:
                            // (, line 58
                            // <-, line 58
                            slice_from("y");
                            break;
                        case 2:
                            // (, line 59
                            // <-, line 59
                            slice_from("u");
                            break;
                        case 3:
                            // (, line 60
                            // <-, line 60
                            slice_from("a");
                            break;
                        case 4:
                            // (, line 61
                            // <-, line 61
                            slice_from("o");
                            break;
                        case 5:
                            // (, line 62
                            // <-, line 62
                            slice_from("u");
                            break;
                        case 6:
                            // (, line 63
                            // next, line 63
                            if (cursor >= limit)
                            {
                                goto lab1;
                            }
                            cursor++;
                            break;
                    }
                    // LUCENENET NOTE: continue label is not supported directly in .NET,
                    // so we just need to add another goto to get to the end of the outer loop.
                    // See: http://stackoverflow.com/a/359449/181087

                    // Original code:
                    //continue replab0;

                    goto end_of_outer_loop;
                    
                } while (false);
                lab1:
                cursor = v_1;
                goto replab0;
                end_of_outer_loop: { }
            }
            replab0:
            return true;
        }

        private bool r_R1()
        {
            if (!(I_p1 <= cursor))
            {
                return false;
            }
            return true;
        }

        private bool r_R2()
        {
            if (!(I_p2 <= cursor))
            {
                return false;
            }
            return true;
        }

        private bool r_standard_suffix()
        {
            int among_var;
            int v_1;
            int v_2;
            int v_3;
            int v_4;
            int v_5;
            int v_6;
            int v_7;
            int v_8;
            int v_9;
            // (, line 73
            // do, line 74
            v_1 = limit - cursor;
            do
            {
                // (, line 74
                // [, line 75
                ket = cursor;
                // substring, line 75
                among_var = find_among_b(a_1, 7);
                if (among_var == 0)
                {
                    goto lab0;
                }
                // ], line 75
                bra = cursor;
                // call R1, line 75
                if (!r_R1())
                {
                    goto lab0;
                }
                switch (among_var)
                {
                    case 0:
                        goto lab0;
                    case 1:
                        // (, line 77
                        // delete, line 77
                        slice_del();
                        break;
                    case 2:
                        // (, line 80
                        if (!(in_grouping_b(g_s_ending, 98, 116)))
                        {
                            goto lab0;
                        }
                        // delete, line 80
                        slice_del();
                        break;
                }
            } while (false);
            lab0:
            cursor = limit - v_1;
            // do, line 84
            v_2 = limit - cursor;
            do
            {
                // (, line 84
                // [, line 85
                ket = cursor;
                // substring, line 85
                among_var = find_among_b(a_2, 4);
                if (among_var == 0)
                {
                    goto lab1;
                }
                // ], line 85
                bra = cursor;
                // call R1, line 85
                if (!r_R1())
                {
                    goto lab1;
                }
                switch (among_var)
                {
                    case 0:
                        goto lab1;
                    case 1:
                        // (, line 87
                        // delete, line 87
                        slice_del();
                        break;
                    case 2:
                        // (, line 90
                        if (!(in_grouping_b(g_st_ending, 98, 116)))
                        {
                            goto lab1;
                        }
                        // hop, line 90
                        {
                            int c = cursor - 3;
                            if (limit_backward > c || c > limit)
                            {
                                goto lab1;
                            }
                            cursor = c;
                        }
                        // delete, line 90
                        slice_del();
                        break;
                }
            } while (false);
            lab1:
            cursor = limit - v_2;
            // do, line 94
            v_3 = limit - cursor;
            do
            {
                // (, line 94
                // [, line 95
                ket = cursor;
                // substring, line 95
                among_var = find_among_b(a_4, 8);
                if (among_var == 0)
                {
                    goto lab2;
                }
                // ], line 95
                bra = cursor;
                // call R2, line 95
                if (!r_R2())
                {
                    goto lab2;
                }
                switch (among_var)
                {
                    case 0:
                        goto lab2;
                    case 1:
                        // (, line 97
                        // delete, line 97
                        slice_del();
                        // try, line 98
                        v_4 = limit - cursor;
                        do
                        {
                            // (, line 98
                            // [, line 98
                            ket = cursor;
                            // literal, line 98
                            if (!(eq_s_b(2, "ig")))
                            {
                                cursor = limit - v_4;
                                goto lab3;
                            }
                            // ], line 98
                            bra = cursor;
                            // not, line 98
                            {
                                v_5 = limit - cursor;
                                do
                                {
                                    // literal, line 98
                                    if (!(eq_s_b(1, "e")))
                                    {
                                        goto lab4;
                                    }
                                    cursor = limit - v_4;
                                    goto lab3;
                                } while (false);
                                lab4:
                                cursor = limit - v_5;
                            }
                            // call R2, line 98
                            if (!r_R2())
                            {
                                cursor = limit - v_4;
                                goto lab3;
                            }
                            // delete, line 98
                            slice_del();
                        } while (false);
                        lab3:
                        break;
                    case 2:
                        // (, line 101
                        // not, line 101
                        {
                            v_6 = limit - cursor;
                            do
                            {
                                // literal, line 101
                                if (!(eq_s_b(1, "e")))
                                {
                                    goto lab5;
                                }
                                goto lab2;
                            } while (false);
                            lab5:
                            cursor = limit - v_6;
                        }
                        // delete, line 101
                        slice_del();
                        break;
                    case 3:
                        // (, line 104
                        // delete, line 104
                        slice_del();
                        // try, line 105
                        v_7 = limit - cursor;
                        do
                        {
                            // (, line 105
                            // [, line 106
                            ket = cursor;
                            // or, line 106
                            do
                            {
                                v_8 = limit - cursor;
                                do
                                {
                                    // literal, line 106
                                    if (!(eq_s_b(2, "er")))
                                    {
                                        goto lab8;
                                    }
                                    goto lab7;
                                } while (false);
                                lab8:
                                cursor = limit - v_8;
                                // literal, line 106
                                if (!(eq_s_b(2, "en")))
                                {
                                    cursor = limit - v_7;
                                    goto lab6;
                                }
                            } while (false);
                            lab7:
                            // ], line 106
                            bra = cursor;
                            // call R1, line 106
                            if (!r_R1())
                            {
                                cursor = limit - v_7;
                                goto lab6;
                            }
                            // delete, line 106
                            slice_del();
                        } while (false);
                        lab6:
                        break;
                    case 4:
                        // (, line 110
                        // delete, line 110
                        slice_del();
                        // try, line 111
                        v_9 = limit - cursor;
                        do
                        {
                            // (, line 111
                            // [, line 112
                            ket = cursor;
                            // substring, line 112
                            among_var = find_among_b(a_3, 2);
                            if (among_var == 0)
                            {
                                cursor = limit - v_9;
                                goto lab9;
                            }
                            // ], line 112
                            bra = cursor;
                            // call R2, line 112
                            if (!r_R2())
                            {
                                cursor = limit - v_9;
                                goto lab9;
                            }
                            switch (among_var)
                            {
                                case 0:
                                    cursor = limit - v_9;
                                    goto lab9;
                                case 1:
                                    // (, line 114
                                    // delete, line 114
                                    slice_del();
                                    break;
                            }
                        } while (false);
                        lab9:
                        break;
                }
            } while (false);
            lab2:
            cursor = limit - v_3;
            return true;
        }

        
                public override bool Stem()
        {
            int v_1;
            int v_2;
            int v_3;
            int v_4;
            // (, line 124
            // do, line 125
            v_1 = cursor;
             do
            {
                // call prelude, line 125
                if (!r_prelude())
                {
                    goto lab0;
                }
            } while (false);
            lab0:
            cursor = v_1;
            // do, line 126
            v_2 = cursor;
            do
            {
                // call mark_regions, line 126
                if (!r_mark_regions())
                {
                    goto lab1;
                }
            } while (false);
            lab1:
            cursor = v_2;
            // backwards, line 127
            limit_backward = cursor; cursor = limit;
            // do, line 128
            v_3 = limit - cursor;
            do
            {
                // call standard_suffix, line 128
                if (!r_standard_suffix())
                {
                    goto lab2;
                }
            } while (false);
            lab2:
            cursor = limit - v_3;
            cursor = limit_backward;                    // do, line 129
            v_4 = cursor;
            do
            {
                // call postlude, line 129
                if (!r_postlude())
                {
                    goto lab3;
                }
            } while (false);
            lab3:
            cursor = v_4;
            return true;
        }

        public override bool Equals(object o)
        {
            return o is GermanStemmer;
        }

        public override int GetHashCode()
        {
            return this.GetType().FullName.GetHashCode();
        }
    }
}
